import { Inter } from 'next/font/google'

import { ClusterProvider } from '@/components/cluster/cluster-data-access'
import Header from '@/components/layout/header'
import { SolanaProvider } from '@/components/solana/solana-provider'
import { ThemeProvider } from '@/config/ThemeProvider'

import './globals.css'
import { ReactQueryProvider } from './react-query-provider'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Yapdotfun',
  description: 'Generated by create-solana-dapp'
}
export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <ClusterProvider>
              <SolanaProvider>
                <Header />
                {children}
                {/* <UiLayout links={links}>{children}</UiLayout> */}
              </SolanaProvider>
            </ClusterProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
