name: Test and Build Anchor

on:
  push:
    branches: ['release/*']
  pull_request:
    branches: ['devel']

env:
  HUSKY: 0

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: metadaoproject/setup-anchor@v3
        with:
          anchor-version: '0.30.1'
          node-version: '20'

      - name: Generate new keypair
        run: solana-keygen new --no-bip39-passphrase

      - name: Set solana target cluster to local
        run: solana config set --url http://localhost:8899

      - name: Check solana config
        run: solana config get

      - run: cd anchor && rm Cargo.lock && cd ../
        shell: bash

      - run: sh -c "$(curl -sSfL https://release.anza.xyz/v2.2.3/install)"
        shell: bash

      - run: pnpm run anchor build
        shell: bash

      - run: pnpm run anchor test
        shell: bash
